# Assignment 1

## NumPy 

In [2]:
import numpy as np

### Multi-dimensional arrays

In [3]:

arr1=np.array([1,2,3]) #one dimensional array

arr2 = np.array([[[1,2,3], [4,5,6]], 
[[7,8,9], [10,11,12]],
[[13,14,15], [16,17,18]],
[[1,14,15], [12,17,18]]]) # 4 dimensional array

print (arr1,"\n\n",arr2)

#shape()
np.shape(arr2) 

[1 2 3] 

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[ 1 14 15]
  [12 17 18]]]


(4, 2, 3)

In [21]:
#To create an array with 1's of given shape
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#Creating arrays with given elements and given shape
np.full((2,1), 1.1) 

array([[1.1],
       [1.1]])

In [29]:
#Generate requested number of samples given lower and upper limits (stop included)
np.linspace(0,8,4)

array([0.        , 2.66666667, 5.33333333, 8.        ])

In [28]:
#Generate all the elements within given limits with step
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
#Generate random data with Normal distribution
np.random.normal(8,2,(4,1))

array([[11.12934235],
       [ 5.12524233],
       [ 6.74906362],
       [ 8.96104146]])

In [53]:
#Generate Random data of given shape
x=np.random.random((3,2,2))
x

array([[[0.42471613, 0.33736747],
        [0.90331023, 0.65659374]],

       [[0.27240551, 0.54617516],
        [0.72398438, 0.88230134]],

       [[0.08138515, 0.60170357],
        [0.81486237, 0.68122836]]])

In [54]:
#Validating the shape of above array generated random
x.shape

(3, 2, 2)

In [55]:
#To get size of above array generated random with size function
x.size

12

In [56]:
#To get the dimension of the above generated array
x.ndim

3

### Computations on NumPy

In [200]:
#Binary operations 

x=np.array([[1,1],[2,2]])
y=np.array([[3, 4],[6, 5]])
print("\nBinary Operations:\n")
print ("Multiplication %s\nAddition %s\nDifference %s\nModulus %s\nFloor division%s\nExponentiation%s\n "%((x*y),(x+y),(x-y),(x%y),(x//y),(x**y)))


Binary Operations:

Multiplication [[ 3  4]
 [12 10]]
Addition [[4 5]
 [8 7]]
Difference [[-2 -3]
 [-4 -3]]
Modulus [[1 1]
 [2 2]]
Floor division[[0 0]
 [0 0]]
Exponentiation[[ 1  1]
 [64 32]]
 


In [76]:
#Unary operations 

print("\nUnary operations:\n")
print ("exponentiation%s\nlog2%s\nlog10%s\nAbs%s\nsin%s\ncos%s\ntan%s\n"%(np.exp(x),np.log2(x),np.log10(x),np.abs(x),np.sin(x),np.cos(x),np.tan(x)))


Unary operations:

exponentiation[[2.71828183 2.71828183]
 [7.3890561  7.3890561 ]]
log2[[0. 0.]
 [1. 1.]]
log10[[0.      0.     ]
 [0.30103 0.30103]]
Abs[[1 1]
 [2 2]]
sin[[0.84147098 0.84147098]
 [0.90929743 0.90929743]]
cos[[ 0.54030231  0.54030231]
 [-0.41614684 -0.41614684]]
tan[[ 1.55740772  1.55740772]
 [-2.18503986 -2.18503986]]



### Aggregate functions

In [81]:

print("\nAggregate Functions:\n")
print ("Min %s\nMax %s\nArgmin %s\nArgmax %s\nMean %s\nStd %s\nSum %s\n"%(np.min(x),np.max(x),np.argmin(x),np.argmax(x),x.mean(),x.std(),np.sum(x)))


Aggregate Functions:

Min 1
Max 2
Argmin 0
Argmax 2
Mean 1.5
Std 0.5
Sum 6



In [94]:
x=np.array([[1,7],[2,4]])
print(x)

[[1 7]
 [2 4]]


    
    * Argmax(),Argmin() functions return the indices of the max and min elements respectively in given axes. In the above array, along axis 1, which is in the direction of columns comparison is made between (1,7) and (2,4) and the positions of 7 and 4 are returned below as [1,1] *
     

In [98]:
x.argmax(axis=1)

array([1, 1])

In [99]:
#Returns the sum of elements in given axis
x.sum(axis=0)

array([ 3, 11])

In [108]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print (x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


    
* Considering the above 3D array, min function identifies the min elements in the last axis (elements of each row within each matrix in this case) resulting in 2 elements per matrix in the array. Thus, element of the aggregation dimension is removed in the output.

Similarly in the following cell, when axis 1 is considered, each rows are considered, hence min element between the rows of the same matrix are identified, removal of axis 1 makes the output an array of size (3,3) *
    

In [114]:
x.min(axis=-1)

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [115]:
x.min(axis=1)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

###Sorting

In [125]:
y = np.array([[2,7,3],[7,2,1]])
np.sort(y)

array([[2, 3, 7],
       [1, 2, 7]])

In [126]:
#Original array unchanged as sort creates a copy
print(y)

[[2 7 3]
 [7 2 1]]


In [127]:
np.sort(y,axis=0)

array([[2, 2, 1],
       [7, 7, 3]])

In [128]:
#Returns the only the indices of the array and not values
np.argsort(y)

array([[0, 2, 1],
       [2, 1, 0]])

### Algebraic Operations

In [129]:

#dot operator - multiplication 

x=np.array([1, 2, 3])
y=np.array([0, 2, 1])

np.dot(x,y)

7

In [130]:
x=np.array([[1,1],[2,2]])
y=np.array([2, 3])
np.dot(x, y)

array([ 5, 10])

In [131]:
x=np.array([[1,1],[2,2]])
y=np.array([[2,2],[1,1]])

np.dot(x, y)

array([[3, 3],
       [6, 6]])

### Broadcasting

 * Broadcasting is the functionality provided by numpy to handle arrays of different dimensions as compatible to each other either by padding or stretching based on the rules of broadcasting,

1, The last dimension has to match for both arrays or one of the arrays is one dimensional
2, If dimension of both arrays are >1 and if the shapes mismatch, broadcasting cannot be performed (throws value error) *

In [133]:


x = np.array([1, 2, 3])
y = np.array([[11], [12], [13]])
z = x + y
z

array([[12, 13, 14],
       [13, 14, 15],
       [14, 15, 16]])

In [134]:
#Broadcasting error scenario

x = np.array([[1, 2],[3,4],[5,6]])
y = np.array([11, 12, 13])

z = x + y

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### Accessing NumPy Arrays

In [136]:
#Simple indexing

x = np.array([[2, 3, 4],[5,6,7]])
el = x[1, 2]
el

7

In [137]:
#Value assignment
x[1, 2] = 1
x

array([[2, 3, 4],
       [5, 6, 1]])

In [139]:
x[1, -2]

6

In [140]:
#Slicing
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [141]:
#To access elements contiguously
x[:2, ::2]

array([[1, 3],
       [4, 6]])

In [143]:
#Update using slicing

x[:, 1:] = 0
print (x) #Updates the original array rather than producing a copy

[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [147]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
view = x[:,1:]
view[:,:] = 0
print(x)

[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [150]:
#Using copy() to avoid overwriting
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x1=x[:,1:].copy()
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
#Masking

x2 = np.array([[1.2, 6.1], [1.5, 4.5]])
#x2 >= 4
~((x2 < 1) | (x2 > 5))

array([[ True, False],
       [ True,  True]])

In [154]:
x2[x2 >= 4]

array([6.1, 4.5])

In [158]:
#Update masked array
x = np.array([1.2, 4.1, 1.5, 4.5])
x[x > 4] = 0
x


array([1.2, 0. , 1.5, 0. ])

In [159]:
#Fancy indexing
x = np.array([7.0, 9.0, 6.0, 5.0])
x[[1, 3]]#Handpicking the elements with indices


array([9., 5.])

In [160]:
#Fancy indexing 2D arrays
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0],
[6.0, 7.0, 8.0]])

x[[1, 2]]


array([[3., 4., 5.],
       [6., 7., 8.]])

In [161]:
#Element level selection

x[[1, 2], [0, 2]]

array([3., 8.])

In [162]:
#Combined indexing - Masking + slicing

x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])

x[[True,False,True], 1:]

array([[1., 2.],
       [7., 8.]])

In [163]:
#Combined indexing - Fancy + Slicing
x[[0,2], :2]

array([[0., 1.],
       [6., 7.]])

In [164]:
#Combined indexing - Simple + Slicing:
x[0, 1:]


array([1., 2.])

In [165]:
#Combined indexing - Simple + Masking:
x[[True, False, True], 0]

array([0., 6.])

### Working With Arrays

In [183]:
#Array concatenation

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
print(np.concatenate((x, y)))


[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [185]:
#Array concatenation along axis

print(np.concatenate((x, y), axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [172]:
#Array concatenation : hstack

h = np.hstack((x, y))
print (h)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [174]:
#Array concatenation : vstack
v = np.vstack((x, y))
print (v)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [188]:
#Array concatenation :vstack 1-D
x = np.array([1,2,3])
y = np.array([11,12,13])
print (np.vstack((x, y)))
print(np.concatenate((x, y), axis=0)) #concatenates along same axis

[[ 1  2  3]
 [11 12 13]]
[ 1  2  3 11 12 13]


In [189]:
#Splitting arrays

x = np.array([7, 7, 9, 9, 8, 8])
np.split(x,[2,4]) #Array x split at 2 and 4

[array([7, 7]), array([9, 9]), array([8, 8])]

In [191]:
#hsplit
np.hsplit(x, [3])

[array([7, 7, 9]), array([9, 8, 8])]

In [194]:
#vsplit
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
z=np.concatenate((x,y), axis=0)
np.vsplit(z, [2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [195]:
#Reshape
x = np.arange(6)
y = x.reshape((2,3))
y

array([[0, 1, 2],
       [3, 4, 5]])

In [197]:
#Reshaping with unknown dimension
x = np.array([1,2,3])
y = x.reshape(-1,1)
y

array([[1],
       [2],
       [3]])

In [198]:
#Reshaping - new dimension

arr = np.array([[1,2,3],[4,5,6]])
res = arr[np.newaxis, :, :]
print(res)

[[[1 2 3]
  [4 5 6]]]


In [199]:
arr = np.array([1,2,3])
res = arr[:, np.newaxis]
print (res)

[[1]
 [2]
 [3]]
